name: Paul Meyers
favicon: null
layout_spectrum: 0.27791215875186026
typography_spectrum: 0.4362224468495697
title: Motorcycling - Technology - Automotive
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09379391907714307
  lightness: 0.7730302684940398
  saturation: 0.5213447024580091
  rhythmicContrast: 0.511283682892099
purpose: []
